 const currencyOptions = [
    { value: 'USD', label: 'United States Dollar (USD)' },
    { value: 'EUR', label: 'Euro (EUR)' },
    { value: 'GBP', label: 'British Pound (GBP)' },
    { value: 'JPY', label: 'Japanese Yen (JPY)' },
    { value: 'CNY', label: 'Chinese Yuan (CNY)' },
    { value: 'INR', label: 'Indian Rupee (INR)' },
    { value: 'AUD', label: 'Australian Dollar (AUD)' },
    { value: 'CAD', label: 'Canadian Dollar (CAD)' },
    { value: 'SGD', label: 'Singapore Dollar (SGD)' },
    { value: 'CHF', label: 'Swiss Franc (CHF)' },
    { value: 'MYR', label: 'Malaysian Ringgit (MYR)' },
    { value: 'NZD', label: 'New Zealand Dollar (NZD)' },
    { value: 'THB', label: 'Thai Baht (THB)' },
    { value: 'HUF', label: 'Hungarian Forint (HUF)' },
    { value: 'SEK', label: 'Swedish Krona (SEK)' },
    { value: 'NOK', label: 'Norwegian Krone (NOK)' },
    { value: 'TRY', label: 'Turkish Lira (TRY)' },
    { value: 'RUB', label: 'Russian Ruble (RUB)' },
    { value: 'BRL', label: 'Brazilian Real (BRL)' },
    { value: 'ZAR', label: 'South African Rand (ZAR)' },
    { value: 'MXN', label: 'Mexican Peso (MXN)' },
    { value: 'ARS', label: 'Argentine Peso (ARS)' },
    { value: 'IDR', label: 'Indonesian Rupiah (IDR)' },
    { value: 'KRW', label: 'South Korean Won (KRW)' },
    { value: 'PHP', label: 'Philippine Peso (PHP)' },
    { value: 'PLN', label: 'Polish Złoty (PLN)' },
    { value: 'ILS', label: 'Israeli Shekel (ILS)' },
    { value: 'CZK', label: 'Czech Koruna (CZK)' },
    { value: 'COP', label: 'Colombian Peso (COP)' },
    { value: 'CLP', label: 'Chilean Peso (CLP)' },
    { value: 'EGP', label: 'Egyptian Pound (EGP)' },
    { value: 'AED', label: 'United Arab Emirates Dirham (AED)' },
    { value: 'SAR', label: 'Saudi Riyal (SAR)' },
    { value: 'TWD', label: 'Taiwan Dollar (TWD)' },
    { value: 'HKD', label: 'Hong Kong Dollar (HKD)' },
    { value: 'DKK', label: 'Danish Krone (DKK)' },
    { value: 'ISK', label: 'Icelandic Króna (ISK)' },
    { value: 'BGN', label: 'Bulgarian Lev (BGN)' },
    { value: 'HRK', label: 'Croatian Kuna (HRK)' },
    { value: 'RON', label: 'Romanian Leu (RON)' },
    { value: 'ISK', label: 'Icelandic Króna (ISK)' },
    { value: 'PLN', label: 'Polish Złoty (PLN)' },
    { value: 'UAH', label: 'Ukrainian Hryvnia (UAH)' },
    { value: 'EGP', label: 'Egyptian Pound (EGP)' },
    { value: 'ZAR', label: 'South African Rand (ZAR)' },
    { value: 'BRL', label: 'Brazilian Real (BRL)' },
    { value: 'ILS', label: 'Israeli Shekel (ILS)' },
    { value: 'CZK', label: 'Czech Koruna (CZK)' },
    { value: 'PLN', label: 'Polish Złoty (PLN)' },
    { value: 'HUF', label: 'Hungarian Forint (HUF)' },
    { value: 'RON', label: 'Romanian Leu (RON)' },
    { value: 'SEK', label: 'Swedish Krona (SEK)' },
    { value: 'NOK', label: 'Norwegian Krone (NOK)' },
    { value: 'DKK', label: 'Danish Krone (DKK)' },
    { value: 'ISK', label: 'Icelandic Króna (ISK)' },
    { value: 'CHF', label: 'Swiss Franc (CHF)' },
    { value: 'RUB', label: 'Russian Ruble (RUB)' },
    { value: 'TRY', label: 'Turkish Lira (TRY)' },
    { value: 'AED', label: 'United Arab Emirates Dirham (AED)' },
    { value: 'SAR', label: 'Saudi Riyal (SAR)' },
    { value: 'QAR', label: 'Qatari Riyal (QAR)' },
    { value: 'BHD', label: 'Bahraini Dinar (BHD)' },
    { value: 'OMR', label: 'Omani Rial (OMR)' },
    { value: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
    { value: 'JOD', label: 'Jordanian Dinar (JOD)' },
    { value: 'LBP', label: 'Lebanese Pound (LBP)' },
    { value: 'EGP', label: 'Egyptian Pound (EGP)' },
    { value: 'ZAR', label: 'South African Rand (ZAR)' },
    { value: 'BRL', label: 'Brazilian Real (BRL)' },
    { value: 'CLP', label: 'Chilean Peso (CLP)' },
    { value: 'ARS', label: 'Argentine Peso (ARS)' },
    { value: 'PEN', label: 'Peruvian Sol (PEN)' },
    { value: 'COP', label: 'Colombian Peso (COP)' },
    { value: 'MXN', label: 'Mexican Peso (MXN)' },
    { value: 'BWP', label: 'Botswana Pula (BWP)' },
    { value: 'GHS', label: 'Ghanaian Cedi (GHS)' },
    { value: 'NGN', label: 'Nigerian Naira (NGN)' },
    { value: 'KES', label: 'Kenyan Shilling (KES)' },
    { value: 'ZMW', label: 'Zambian Kwacha (ZMW)' },
    { value: 'EGP', label: 'Egyptian Pound (EGP)' },
    { value: 'MAD', label: 'Moroccan Dirham (MAD)' },
    { value: 'DZD', label: 'Algerian Dinar (DZD)' },
    { value: 'TND', label: 'Tunisian Dinar (TND)' },
    { value: 'MAD', label: 'Moroccan Dirham (MAD)' },
    { value: 'EUR', label: 'Euro (EUR)' },
    { value: 'GBP', label: 'British Pound (GBP)' },
    { value: 'CHF', label: 'Swiss Franc (CHF)' },
    { value: 'SEK', label: 'Swedish Krona (SEK)' },
    { value: 'NOK', label: 'Norwegian Krone (NOK)' },
    { value: 'DKK', label: 'Danish Krone (DKK)' },
    { value: 'ISK', label: 'Icelandic Króna (ISK)' },
    { value: 'PLN', label: 'Polish Złoty (PLN)' },
    { value: 'RUB', label: 'Russian Ruble (RUB)' },
    { value: 'TRY', label: 'Turkish Lira (TRY)' },
    { value: 'UAH', label: 'Ukrainian Hryvnia (UAH)' },
    { value: 'HUF', label: 'Hungarian Forint (HUF)' },
    { value: 'CZK', label: 'Czech Koruna (CZK)' },
    { value: 'BGN', label: 'Bulgarian Lev (BGN)' },
    { value: 'RON', label: 'Romanian Leu (RON)' },
    { value: 'HRK', label: 'Croatian Kuna (HRK)' },
    { value: 'RSD', label: 'Serbian Dinar (RSD)' },
    { value: 'BAM', label: 'Bosnia and Herzegovina Convertible Mark (BAM)' },
    { value: 'MKD', label: 'Macedonian Denar (MKD)' },
    { value: 'EEK', label: 'Estonian Kroon (EEK)' },
    { value: 'LTL', label: 'Lithuanian Litas (LTL)' },
    { value: 'LVL', label: 'Latvian Lats (LVL)' },
    { value: 'MDL', label: 'Moldovan Leu (MDL)' },
    { value: 'ALL', label: 'Albanian Lek (ALL)' },
    { value: 'BGN', label: 'Bulgarian Lev (BGN)' },
    { value: 'BYN', label: 'Belarusian Ruble (BYN)' },
    { value: 'GEL', label: 'Georgian Lari (GEL)' },
    { value: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
    { value: 'AZN', label: 'Azerbaijani Manat (AZN)' },
    { value: 'AMD', label: 'Armenian Dram (AMD)' },
    { value: 'EUR', label: 'Euro (EUR)' },
    { value: 'CHF', label: 'Swiss Franc (CHF)' },
    { value: 'RUB', label: 'Russian Ruble (RUB)' },
    { value: 'BYN', label: 'Belarusian Ruble (BYN)' },
    { value: 'UAH', label: 'Ukrainian Hryvnia (UAH)' },
    { value: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
    { value: 'GEL', label: 'Georgian Lari (GEL)' },
    { value: 'PLN', label: 'Polish Złoty (PLN)' },
    { value: 'RON', label: 'Romanian Leu (RON)' },
    { value: 'CZK', label: 'Czech Koruna (CZK)' },
    { value: 'HRK', label: 'Croatian Kuna (HRK)' },
    { value: 'HUF', label: 'Hungarian Forint (HUF)' },
    { value: 'SEK', label: 'Swedish Krona (SEK)' },
    { value: 'NOK', label: 'Norwegian Krone (NOK)' },
    { value: 'DKK', label: 'Danish Krone (DKK)' },
    { value: 'ISK', label: 'Icelandic Króna (ISK)' },
    { value: 'GBP', label: 'British Pound (GBP)' },
    { value: 'USD', label: 'United States Dollar (USD)' },
    { value: 'AUD', label: 'Australian Dollar (AUD)' },
    { value: 'CAD', label: 'Canadian Dollar (CAD)' },
    { value: 'SGD', label: 'Singapore Dollar (SGD)' },
    { value: 'NZD', label: 'New Zealand Dollar (NZD)' },
    { value: 'CNY', label: 'Chinese Yuan (CNY)' },
    { value: 'JPY', label: 'Japanese Yen (JPY)' },
  ];
  
  export default currencyOptions;